USE [master]
GO

/****** Object:  Database [MasterGestionale]    Script Date: 30/01/2024 18:56:57 ******/
CREATE DATABASE [MasterGestionale]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MasterGestionale', FILENAME = N'C:\Users\mdeidda\MasterGestionale.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MasterGestionale_log', FILENAME = N'C:\Users\mdeidda\MasterGestionale_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MasterGestionale].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MasterGestionale] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MasterGestionale] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MasterGestionale] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MasterGestionale] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MasterGestionale] SET ARITHABORT OFF 
GO

ALTER DATABASE [MasterGestionale] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MasterGestionale] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MasterGestionale] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MasterGestionale] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MasterGestionale] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MasterGestionale] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MasterGestionale] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MasterGestionale] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MasterGestionale] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MasterGestionale] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MasterGestionale] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MasterGestionale] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MasterGestionale] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MasterGestionale] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MasterGestionale] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MasterGestionale] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [MasterGestionale] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MasterGestionale] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MasterGestionale] SET  MULTI_USER 
GO

ALTER DATABASE [MasterGestionale] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MasterGestionale] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MasterGestionale] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MasterGestionale] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MasterGestionale] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MasterGestionale] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MasterGestionale] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MasterGestionale] SET  READ_WRITE 
GO


